### ISSUE TITLE
behövs ett fält för rental_duration

### ISSUE THREAD

**Issue by cave-bjornson** [cave-bjornson/SakilaFX#14]
https://github.com/cave-bjornson/SakilaFX/blob/3931e19508282598d339a6fd886bd6c2fb8989b0/src/main/java/com/grupp1/entities/Film.java#L31

Tydligen har varje film på lagret ett max antal dagar den får vara uthyrd åt gången. har det i gui:t men inte i klassen. getters och setters också förstås

**Comment by Botolv12** [comment]
fixat problemet, fixade även tostringen så klart.
