### ISSUE TITLE
Testar Issues

### ISSUE THREAD

**Issue by cave-bjornson** [cave-bjornson/SakilaFX#7]
Hallihallå! Om ni ser det här funkar notifications för issues! Kanon! Pröva att kommentera och close så kommer jag få ett email om det.

**Comment by cave-bjornson** [comment]
Eller tryck ev inte close innan alla sett den...

**Comment by sebastianhogvall** [comment]
Jag fick en notis om detta björn!

**Comment by Dj0ser** [comment]
Fick email 👍


Den fre 27 mars 2020 13:46sebastianhogvall <notifications@github.com> skrev:

**Comment by LisaPahn** [comment]
Jag med!

Skickat från min iPhone

27 mars 2020 kl. 14:02 skrev Carl-Rehn <notifications@github.com<mailto:notifications@github.com>>:


Fick email 👍


Den fre 27 mars 2020 13:46sebastianhogvall <notifications@github.com<mailto:notifications@github.com>> skrev:

**Comment by cave-bjornson** [comment]
Jättebra! Stänger nu så slut på spam.
